### ISSUE TITLE
Create a release process to release to maven central

### ISSUE THREAD

**Issue by deaktator** [multiworldtesting/explore-java#5]
It would be nice to have this artifact available on maven central.  I could help with this if you would like.

**Comment by lhoang29** [comment]
If it doesn't take much time, please go ahead. I'm not too familiar with maven central.

**Comment by jmorra** [comment]
I have taken the liberty of doing most of the work in pull request #6.

**Comment by jmorra** [comment]
I think this can probably be closed as we've just had our first successful release [here](https://oss.sonatype.org/content/repositories/releases/com/github/multiworldtesting/explore-java/1.0.0/).  It'll be synched with Maven Central soon.  Also, please enable the Travis build from the MWT account [here](https://travis-ci.org/profile/multiworldtesting) (I don't have admin access).  I have updated the badge to point to the appropriate account, and this will not work until someone with admin access flicks the switch on Travis.

**Comment by lhoang29** [comment]
Thanks! I turned the switch on and committed an update to the README, we should be all set. Closing.
